name = "julia_optym"
uuid = "81397f94-8540-4dcf-be4b-c90671be9d35"
authors = ["Karol Kapłanek"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]